In [18]:
import pandas as pd

# Cars

In [19]:
df = pd.read_csv('../../data/cars.csv')
df.head()

,ID,Make,Model,Year,Trim,Trim (description),Base MSRP,Base Invoice,Colors exterior,Colors interior,...,Towing and hauling,Safety features,Packages,Exterior options,Interior options,Mechanical options,Domestic / imported,Country of origin,Car classification,Platform code / generation number
0,401935490,BMW,3 Series,2023,330i,330i 4dr Sedan (2.0L 4cyl Turbo 8A),"$42,300","$39,840","Portimao Blue Metallic(66,89,154);Mineral Whit...","Canberra Beige SensaTec, leatherette(217,211,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,Imported,Germany,Compact car,G20
1,401953112,BMW,3 Series,2023,330e,330e 4dr Sedan (2.0L 4cyl Turbo gas/electric p...,"$43,300","$40,770","Portimao Blue Metallic(66,89,154);Mineral Whit...","Canberra Beige SensaTec, leatherette(217,211,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,Imported,Germany,Compact car,G20
2,401953111,BMW,3 Series,2023,M340i,M340i 4dr Sedan (3.0L 6cyl Turbo gas/electric ...,"$54,850","$51,510","Portimao Blue Metallic(66,89,154);Mineral Whit...","Canberra Beige SensaTec, leatherette(217,211,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,Imported,Germany,Compact car,G20
3,401953113,BMW,3 Series,2023,M340i xDrive,M340i xDrive 4dr Sedan AWD (3.0L 6cyl Turbo ga...,"$56,850","$53,370","Portimao Blue Metallic(66,89,154);Mineral Whit...","Canberra Beige SensaTec, leatherette(217,211,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,Imported,Germany,Compact car,G20
4,401953115,BMW,3 Series,2023,330e xDrive,330e xDrive 4dr Sedan AWD (2.0L 4cyl Turbo gas...,"$45,300","$42,630","Portimao Blue Metallic(66,89,154);Mineral Whit...","Canberra Beige SensaTec, leatherette(217,211,1...",...,NaN,NaN,NaN,NaN,NaN,NaN,Imported,Germany,Compact car,G20

In [25]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ID,621.0,NaN,NaN,NaN,175937546.723027,155997246.034976,32.0,100003663.0,101171222.0,401729246.0,401954474.0
Make,621,3,Ford,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,621,4,F-150,336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,621.0,NaN,NaN,NaN,2009.305958,9.736353,1990.0,2002.0,2010.0,2018.0,2023.0
Trim,621,89,XLT,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
Mechanical options,234,90,\n 6-Speed STEPTRON...,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Domestic / imported,621,2,Domestic,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country of origin,621,3,United States,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Car classification,621,2,Full-size pickup truck,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Platform code / generation number,621,17,13th gen,84,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
cols = df.columns
for col in cols:
    print(col)

ID
Make
Model
Year
Trim
Trim (description)
Base MSRP
Base Invoice
Colors exterior
Colors interior
Body type
Doors
Total seating
Length (in)
Width (in)
Height (in)
Wheelbase (in)
Front track (in)
Rear track (in)
Ground clearance (in)
Angle of approach (degrees)
Angle of departure (degrees)
Turning circle (ft)
Drag coefficient (Cd)
EPA interior volume (cu ft)
Cargo capacity (cu ft)
Maximum cargo capacity (cu ft)
Curb weight (lbs)
Gross weight (lbs)
Maximum payload (lbs)
Maximum towing capacity (lbs)
Cylinders
Engine size (l)
Horsepower (HP)
Horsepower (rpm)
Torque (ft-lbs)
Torque (rpm)
Valves
Valve timing
Cam type
Drive type
Transmission
Engine type
Fuel type
Fuel tank capacity (gal)
EPA combined MPG
EPA city/highway MPG
Range in miles (city/hwy)
EPA combined MPGe
EPA city/highway MPGe
EPA electricity range (mi)
EPA kWh/100 mi
EPA time to charge battery (at 240V) (hr)
Battery capacity (kWh)
Front head room (in)
Front hip room (in)
Front leg room (in)
Front shoulder room (in)
Rear head room (in)
Rear hip room (in)
Rear leg room (in)
Rear shoulder room (in)
Basic
Drivetrain
Roadside
Rust
Source JSON
Source URL
Image URL
NHTSA Overall Rating
Scorecard Overall
Scorecard Driving
Scorecard Comfort
Scorecard Interior
Scorecard Utility
Scorecard Technology
Expert rating - Our verdict
Expert rating - Driving
Expert rating - Comfort
Expert rating - Interior
Expert rating - Technology
Expert rating - Storage
Expert rating - Economy
Expert rating - Value
Expert rating - Wildcard
Old trim
Old description
Images URL
Suspension
Front seats
Rear seats
Power features
Instrumentation
Convenience
Comfort
Memorized settings
In car entertainment
Roof and glass
Body
Truck features
Tires and wheels
Doors2
Towing and hauling
Safety features
Packages
Exterior options
Interior options
Mechanical options
Domestic / imported
Country of origin
Car classification
Platform code / generation number

In [22]:
get_cols = ["Make", "Model", "Year", "Trim", "Trim (description)", 
            "Base MSRP", "Body type", "Doors", "Total seating", 
            "Curb weight (lbs)", "Cylinders", "Engine size (l)", "Horsepower (HP)", 
            "Torque (ft-lbs)", "Drive type", "Transmission", "Engine type", 
            "Fuel type", "EPA combined MPG", "Country of origin", "Car classification"]
df2 = df[get_cols]
df2.head()

,Make,Model,Year,Trim,Trim (description),Base MSRP,Body type,Doors,Total seating,Curb weight (lbs),...,Engine size (l),Horsepower (HP),Torque (ft-lbs),Drive type,Transmission,Engine type,Fuel type,EPA combined MPG,Country of origin,Car classification
0,BMW,3 Series,2023,330i,330i 4dr Sedan (2.0L 4cyl Turbo 8A),"$42,300",Sedan,4,5.0,3536.0,...,2.0,255,295.0,rear wheel drive,8-speed shiftable automatic,gas,premium unleaded (required),29.0,Germany,Compact car
1,BMW,3 Series,2023,330e,330e 4dr Sedan (2.0L 4cyl Turbo gas/electric p...,"$43,300",Sedan,4,5.0,4180.0,...,2.0,288,310.0,rear wheel drive,8-speed shiftable automatic,plug-in hybrid,premium unleaded (required),NaN,Germany,Compact car
2,BMW,3 Series,2023,M340i,M340i 4dr Sedan (3.0L 6cyl Turbo gas/electric ...,"$54,850",Sedan,4,5.0,3834.0,...,3.0,382,368.0,rear wheel drive,8-speed shiftable automatic,mild hybrid,premium unleaded (required),26.0,Germany,Compact car
3,BMW,3 Series,2023,M340i xDrive,M340i xDrive 4dr Sedan AWD (3.0L 6cyl Turbo ga...,"$56,850",Sedan,4,5.0,3951.0,...,3.0,382,368.0,all wheel drive,8-speed shiftable automatic,mild hybrid,premium unleaded (required),26.0,Germany,Compact car
4,BMW,3 Series,2023,330e xDrive,330e xDrive 4dr Sedan AWD (2.0L 4cyl Turbo gas...,"$45,300",Sedan,4,5.0,4083.0,...,2.0,288,310.0,all wheel drive,8-speed shiftable automatic,plug-in hybrid,premium unleaded (required),NaN,Germany,Compact car

In [26]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 621 entries, 0 to 620
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Make                621 non-null    object
 1   Model               621 non-null    object
 2   Year                621 non-null    int64
 3   Trim                621 non-null    object
 4   Trim (description)  621 non-null    object
 5   Base MSRP           469 non-null    object
 6   Body type           621 non-null    object
 7   Doors               621 non-null    int64
 8   Total seating       469 non-null    float64
 9   Curb weight (lbs)   546 non-null    float64
 10  Cylinders           613 non-null    object
 11  Engine size (l)     613 non-null    float64
 12  Horsepower (HP)     621 non-null    int64
 13  Torque (ft-lbs)     568 non-null    float64
 14  Drive type          621 non-null    object
 15  Transmission        595 non-null    object
 16  Engine type         621 non-null    object
 17  Fuel type           621 non-null    object
 18  EPA combined MPG    608 non-null    float64
 19  Country of origin   621 non-null    object
 20  Car classification  621 non-null    object
dtypes: float64(5), int64(3), object(13)
memory usage: 102.0+ KB

In [23]:
df2.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Make,621,3,Ford,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Model,621,4,F-150,336,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,621.0,NaN,NaN,NaN,2009.305958,9.736353,1990.0,2002.0,2010.0,2018.0,2023.0
Trim,621,89,XLT,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trim (description),621,428,Two 4dr Hatchback (1.8L 4cyl gas/electric hybr...,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Base MSRP,469,425,"$24,200",4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Body type,621,9,Truck (SuperCrew),108,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Doors,621.0,NaN,NaN,NaN,3.504026,1.125396,2.0,2.0,4.0,4.0,5.0
Total seating,469.0,NaN,NaN,NaN,4.991471,0.884295,3.0,5.0,5.0,6.0,6.0
Curb weight (lbs),546.0,NaN,NaN,NaN,4036.749084,821.814351,2745.0,3287.5,3906.5,4668.0,5863.0
Cylinders,613,4,I6,191,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Engine size (l),613.0,NaN,NaN,NaN,3.482708,1.259186,1.5,2.5,3.3,4.9,5.8
Horsepower (HP),621.0,NaN,NaN,NaN,241.89533,94.474371,110.0,145.0,231.0,300.0,563.0
Torque (ft-lbs),568.0,NaN,NaN,NaN,284.806338,106.066372,82.0,253.0,265.0,365.0,775.0
Drive type,621,4,rear wheel drive,297,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Transmission,595,11,5-speed manual,140,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Engine type,621,7,gas,425,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fuel type,621,6,regular unleaded,374,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EPA combined MPG,608.0,NaN,NaN,NaN,23.641447,12.039052,12.0,16.0,20.0,22.0,56.0
Country of origin,621,3,United States,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Car classification,621,2,Full-size pickup truck,344,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Create Objects

In [28]:
df2["Car classification"].value_counts()

Full-size pickup truck    344
Compact car               277
Name: Car classification, dtype: int64

In [30]:
df2["Engine type"].value_counts()

gas                425
hybrid              96
flex-fuel (FFV)     74
diesel              10
electric             8
plug-in hybrid       4
mild hybrid          4
Name: Engine type, dtype: int64

In [ ]:
def Car():

    def __init__(self, make, model, **kwargs):
        self.make = make
        self.model = model
        for key, value in kwargs.items():
            setattr(self, key, value)
    #def